#!/bin/bash
echo "Please provide the full path to parent directory of media library."
read VIDEOPATH

echo "Please provide second mark: (00)-(59)"
echo "Leave blank for default: 05"
read SECONDMARK
case $SECONDMARK in
[0-9][0-9])
	echo "Seconds: $SECONDMARK"
	;;
"")
	SECONDMARK="05"
	echo "Seconds: $SECONDMARK"
	;;
*)
	echo "This is not a valid second mark"
	exit 0
	;;
esac

echo "Please provide minute mark: (00)-(59)"
echo "Leave blank for default: 00"
read MINUTEMARK
case $MINUTEMARK in
[0-9][0-9])
	echo "Minutes: $MINUTEMARK"
	;;
"")
	MINUTEMARK="00"
	echo "Minutes: $MINUTEMARK"
	;;
*)
	echo "This is not a valid minute mark"
	exit 0
	;;
esac

echo "Please provide hour mark: (00)-(99)"
echo "Leave blank for default: 00"
read HOURMARK
case $HOURMARK in
[0-9][0-9])
	echo "Hours: $HOURMARK"
	;;
"")
	HOURMARK="00"
	echo "Hours: $HOURMARK"
	;;
*)
	echo "This is not a valid hour mark"
	exit 0
	;;
esac

echo "Please provide resolution: 1920:1080"
echo "Leave blank for default: 1280:720"
read RESOLUTION
case $RESOLUTION in
[0-9][0-9][0-9][0-9]":"[0-9][0-9][0-9] | [0-9][0-9][0-9][0-9]":"[0-9][0-9][0-9][0-9])
	echo "Resolution: $RESOLUTION"
	;;
"")
	RESOLUTION="1280:720"
	echo "Resolution: $RESOLUTION"
	;;
*)
	echo "This is not a valid resolution"
	exit 0
	;;
esac

echo "Please provide image format: png or jpg"
echo "Leave blank for default: png"
read FORMAT
case $FORMAT in
[p,j][n,p]"g")
	echo "Format: $FORMAT"
	;;
"")
	FORMAT="png"
	echo "Format: $FORMAT"
	;;
*)
	echo "This is not a valid format"
	exit 0
	;;
esac

# Notify network of activity
/usr/bin/notify "Generating ${RESOLUTION%:*}x${RESOLUTION#*:} thumbnails in .$FORMAT format at the $HOURMARK:$MINUTEMARK:$SECONDMARK mark for vidoes found at this path: $VIDEOPATH" maintenance

# Add Debug info to auto generated script
echo "#!/bin/bash" >>autoGeneratedScript.sh
echo "# This script has been auto generated." >>autoGeneratedScript.sh
echo "# It was created to create thumbnails" >>autoGeneratedScript.sh
echo "# from all selected video files within" >>autoGeneratedScript.sh
echo "# the current directory:" >>autoGeneratedScript.sh
echo "# $VIDEOPATH" >>autoGeneratedScript.sh
echo "#" >>autoGeneratedScript.sh
echo "# Thumbnail specs:" >>autoGeneratedScript.sh
echo "# Frame: $HOURMARK:$MINUTEMARK:$SECONDMARK" >>autoGeneratedScript.sh
echo "# Resolution: ${RESOLUTION%:*}x${RESOLUTION#*:}" >>autoGeneratedScript.sh
echo "# Format: $FORMAT" >>autoGeneratedScript.sh
echo "######################################" >>autoGeneratedScript.sh
echo "# SCRIPT BEGINNING" >>autoGeneratedScript.sh
echo "######################################" >>autoGeneratedScript.sh

# Append a list of file paths that lead to individual video files.
# This script currently supports videos in the .mp4 and .mov formats.
find "$VIDEOPATH" -name '*.m*' -type f -exec ls '{}' \; >>./autoGeneratedScript.sh

# Insert filenames into custom ffmpeg command.
sed -e "s/\/media/'\/media/" -i ./autoGeneratedScript.sh
sed -e "s/\.mp4/\.mp4\'/" -i ./autoGeneratedScript.sh
sed -e "s/\.mov/\.mov\'/" -i ./autoGeneratedScript.sh
sed -e "s/\('.*'\)/ffmpeg -y -ss $HOURMARK:$MINUTEMARK:$SECONDMARK -i \1 -vf "scale="$RESOLUTION"" -frames:v 1 \1\.$FORMAT/" -i ./autoGeneratedScript.sh
sed -e "s/\.mp4'\.$FORMAT/\.$FORMAT'/" -i ./autoGeneratedScript.sh
sed -e "s/\.mov'\.$FORMAT/\.$FORMAT'/" -i ./autoGeneratedScript.sh
sed -e "s~# ffmpeg -y -ss $HOURMARK:$MINUTEMARK:$SECONDMARK -i '$VIDEOPATH' -vf "scale="$RESOLUTION"" -frames:v 1 '${VIDEOPATH%.m*}\.$FORMAT'~# $VIDEOPATH~" -i ./autoGeneratedScript.sh

# Make auto generated script executable...
chmod +x ./autoGeneratedScript.sh

# Uncomment to see the contents of the
# autogenerated script.
#cat autoGeneratedScript.sh

# Execute auto generated script then notify
# network of either a successful or errored
# execution...
./autoGeneratedScript.sh && /usr/bin/notify "Succeeded in generating all thumbnails!" maintenance || /usr/bin/notify "Errors were encountered while generating thumbnails" maintenance

# Clean up auto generated script...
echo "Removing autogenerated script..."
rm ./autoGeneratedScript.sh
