#!/bin/bash
echo "Please provide the full path to parent directory of media library."
read VIDEOPATH

/usr/bin/notify "Generating thumbnails at the 20 second mark for vidoes found at this path: $VIDEOPATH" maintenance

find "$VIDEOPATH" -name '*.m*' -type f -exec ls '{}' \; >>./autoGeneratedScript.sh
sed -e "s/\/media/'\/media/" -i ./autoGeneratedScript.sh
sed -e "s/mp4/mp4\'/" -i ./autoGeneratedScript.sh
sed -e "s/mov/mov\'/" -i ./autoGeneratedScript.sh
sed -e "s/\('.*'\)/ffmpeg -y -ss 00:00:20 -i \1 -vf "scale=1280:720" -frames:v 1 \1.png/" -i ./autoGeneratedScript.sh
sed -e "s/.mp4'.png/.png'/" -i ./autoGeneratedScript.sh
sed -e "s/.mov'.png/.png'/" -i ./autoGeneratedScript.sh
chmod +x ./autoGeneratedScript.sh
#cat autoGeneratedScript.sh
./autoGeneratedScript.sh && /usr/bin/notify "Succeeded in generating all thumbnails!" maintenance || /usr/bin/notify "Errors were encountered while generating thumbnails" maintenance
echo "Removing autogenerated script..."
rm ./autoGeneratedScript.sh
